# Generated by Django 5.2.14 on 2026-06-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_birth_date_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='is_immunosuppressed',
            new_name='has_hematuria',
        ),
    ]
