# Generated by Django 5.2.14 on 2026-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('urology', 'Urología'), ('oncology', 'Oncología'), ('pathology', 'Patología'), ('radiology', 'Radiología'), ('other', 'Otro')], default='other', max_length=32),
        ),
    ]
