# Generated by Django 5.2.14 on 2026-05-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = []
