--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO bladder_997;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO bladder_997;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO bladder_997;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_user; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.authentication_user (
    id uuid NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(32) NOT NULL,
    role character varying(16) NOT NULL,
    specialty character varying(32) NOT NULL,
    hospital character varying(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.authentication_user OWNER TO bladder_997;

--
-- Name: authentication_user_groups; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.authentication_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_user_groups OWNER TO bladder_997;

--
-- Name: authentication_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.authentication_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_user_user_permissions; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.authentication_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_user_user_permissions OWNER TO bladder_997;

--
-- Name: authentication_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.authentication_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinical_endoscopicimage; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_endoscopicimage (
    id uuid NOT NULL,
    file_path character varying(512) NOT NULL,
    original_filename character varying(255) NOT NULL,
    file_size_mb numeric(6,2) NOT NULL,
    width_px integer NOT NULL,
    height_px integer NOT NULL,
    image_quality character varying(16) NOT NULL,
    source character varying(16) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    study_id uuid NOT NULL,
    CONSTRAINT clinical_endoscopicimage_height_px_check CHECK ((height_px >= 0)),
    CONSTRAINT clinical_endoscopicimage_width_px_check CHECK ((width_px >= 0))
);


ALTER TABLE public.clinical_endoscopicimage OWNER TO bladder_997;

--
-- Name: clinical_inferenceresult; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_inferenceresult (
    id uuid NOT NULL,
    model_name character varying(120) NOT NULL,
    model_version character varying(64) NOT NULL,
    primary_label character varying(8) NOT NULL,
    risk_level character varying(8) NOT NULL,
    is_malignant boolean NOT NULL,
    confidence_breakdown jsonb NOT NULL,
    analyzed_parameters jsonb NOT NULL,
    cellular_density character varying(16) NOT NULL,
    nuclear_atypia character varying(16) NOT NULL,
    mitotic_rate character varying(16) NOT NULL,
    findings_overview text NOT NULL,
    recommended_action text NOT NULL,
    mask_url character varying(200) NOT NULL,
    processing_time_ms integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image_id uuid NOT NULL,
    CONSTRAINT clinical_inferenceresult_processing_time_ms_check CHECK ((processing_time_ms >= 0))
);


ALTER TABLE public.clinical_inferenceresult OWNER TO bladder_997;

--
-- Name: clinical_modelconfig; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_modelconfig (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    model_name character varying(120) NOT NULL,
    model_version character varying(64) NOT NULL,
    inference_server_url character varying(200) NOT NULL,
    onnx_optimization boolean NOT NULL,
    is_active boolean NOT NULL,
    model_file_path character varying(512) NOT NULL
);


ALTER TABLE public.clinical_modelconfig OWNER TO bladder_997;

--
-- Name: clinical_patient; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_patient (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    patient_code character varying(32) NOT NULL,
    full_name character varying(200) NOT NULL,
    birth_date date NOT NULL,
    gender character varying(16) NOT NULL,
    is_smoker boolean NOT NULL,
    has_previous_bladder_cancer boolean NOT NULL,
    is_immunosuppressed boolean NOT NULL,
    doctor_id uuid NOT NULL
);


ALTER TABLE public.clinical_patient OWNER TO bladder_997;

--
-- Name: clinical_report; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_report (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reference_code character varying(32) NOT NULL,
    institution_name character varying(255) NOT NULL,
    department character varying(255) NOT NULL,
    include_images boolean NOT NULL,
    send_to_ehr boolean NOT NULL,
    physician_signature boolean NOT NULL,
    pdf_url character varying(200) NOT NULL,
    status character varying(16) NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    generated_by_id uuid NOT NULL,
    study_id uuid NOT NULL
);


ALTER TABLE public.clinical_report OWNER TO bladder_997;

--
-- Name: clinical_study; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.clinical_study (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reference_code character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    study_date timestamp with time zone NOT NULL,
    notes text NOT NULL,
    doctor_id uuid NOT NULL,
    patient_id uuid NOT NULL
);


ALTER TABLE public.clinical_study OWNER TO bladder_997;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO bladder_997;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO bladder_997;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bladder_997;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO bladder_997;

--
-- Name: patients_patient; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.patients_patient (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    patient_code character varying(32) NOT NULL,
    full_name character varying(200) NOT NULL,
    birth_date date NOT NULL,
    gender character varying(16) NOT NULL,
    is_smoker boolean NOT NULL,
    has_previous_bladder_cancer boolean NOT NULL,
    is_immunosuppressed boolean NOT NULL,
    doctor_id uuid NOT NULL
);


ALTER TABLE public.patients_patient OWNER TO bladder_997;

--
-- Name: reports_report; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.reports_report (
    id uuid NOT NULL,
    reference_code character varying(32) NOT NULL,
    institution_name character varying(255) NOT NULL,
    department character varying(255) NOT NULL,
    include_images boolean NOT NULL,
    send_to_ehr boolean NOT NULL,
    physician_signature boolean NOT NULL,
    pdf_url character varying(200) NOT NULL,
    status character varying(16) NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    generated_by_id uuid NOT NULL,
    study_id uuid NOT NULL
);


ALTER TABLE public.reports_report OWNER TO bladder_997;

--
-- Name: studies_endoscopicimage; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.studies_endoscopicimage (
    id uuid NOT NULL,
    file_path character varying(512) NOT NULL,
    original_filename character varying(255) NOT NULL,
    file_size_mb numeric(6,2) NOT NULL,
    width_px integer NOT NULL,
    height_px integer NOT NULL,
    image_quality character varying(16) NOT NULL,
    source character varying(16) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    study_id uuid NOT NULL,
    CONSTRAINT studies_endoscopicimage_height_px_check CHECK ((height_px >= 0)),
    CONSTRAINT studies_endoscopicimage_width_px_check CHECK ((width_px >= 0))
);


ALTER TABLE public.studies_endoscopicimage OWNER TO bladder_997;

--
-- Name: studies_inferenceresult; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.studies_inferenceresult (
    id uuid NOT NULL,
    model_name character varying(120) NOT NULL,
    model_version character varying(64) NOT NULL,
    primary_label character varying(8) NOT NULL,
    risk_level character varying(8) NOT NULL,
    is_malignant boolean NOT NULL,
    confidence_breakdown jsonb NOT NULL,
    analyzed_parameters jsonb NOT NULL,
    cellular_density character varying(16) NOT NULL,
    nuclear_atypia character varying(16) NOT NULL,
    mitotic_rate character varying(16) NOT NULL,
    findings_overview text NOT NULL,
    recommended_action text NOT NULL,
    mask_url character varying(200) NOT NULL,
    processing_time_ms integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image_id uuid NOT NULL,
    CONSTRAINT studies_inferenceresult_processing_time_ms_check CHECK ((processing_time_ms >= 0))
);


ALTER TABLE public.studies_inferenceresult OWNER TO bladder_997;

--
-- Name: studies_modelconfig; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.studies_modelconfig (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    model_name character varying(120) NOT NULL,
    model_version character varying(64) NOT NULL,
    inference_server_url character varying(200) NOT NULL,
    onnx_optimization boolean NOT NULL,
    is_active boolean NOT NULL,
    model_file_path character varying(512) NOT NULL
);


ALTER TABLE public.studies_modelconfig OWNER TO bladder_997;

--
-- Name: studies_study; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.studies_study (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reference_code character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    study_date timestamp with time zone NOT NULL,
    notes text NOT NULL,
    doctor_id uuid NOT NULL,
    patient_id uuid NOT NULL
);


ALTER TABLE public.studies_study OWNER TO bladder_997;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO bladder_997;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: bladder_997
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO bladder_997;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: bladder_997
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_user authentication_user_email_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_email_key UNIQUE (email);


--
-- Name: authentication_user_groups authentication_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_groups authentication_user_groups_user_id_group_id_8af031ac_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_user_id_group_id_8af031ac_uniq UNIQUE (user_id, group_id);


--
-- Name: authentication_user authentication_user_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_user_permissions authentication_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_user_permissions authentication_user_user_user_id_permission_id_ec51b09f_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_user_id_permission_id_ec51b09f_uniq UNIQUE (user_id, permission_id);


--
-- Name: clinical_endoscopicimage clinical_endoscopicimage_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_endoscopicimage
    ADD CONSTRAINT clinical_endoscopicimage_pkey PRIMARY KEY (id);


--
-- Name: clinical_inferenceresult clinical_inferenceresult_image_id_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_inferenceresult
    ADD CONSTRAINT clinical_inferenceresult_image_id_key UNIQUE (image_id);


--
-- Name: clinical_inferenceresult clinical_inferenceresult_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_inferenceresult
    ADD CONSTRAINT clinical_inferenceresult_pkey PRIMARY KEY (id);


--
-- Name: clinical_modelconfig clinical_modelconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_modelconfig
    ADD CONSTRAINT clinical_modelconfig_pkey PRIMARY KEY (id);


--
-- Name: clinical_patient clinical_patient_patient_code_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_patient
    ADD CONSTRAINT clinical_patient_patient_code_key UNIQUE (patient_code);


--
-- Name: clinical_patient clinical_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_patient
    ADD CONSTRAINT clinical_patient_pkey PRIMARY KEY (id);


--
-- Name: clinical_report clinical_report_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_report
    ADD CONSTRAINT clinical_report_pkey PRIMARY KEY (id);


--
-- Name: clinical_report clinical_report_study_id_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_report
    ADD CONSTRAINT clinical_report_study_id_key UNIQUE (study_id);


--
-- Name: clinical_study clinical_study_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_study
    ADD CONSTRAINT clinical_study_pkey PRIMARY KEY (id);


--
-- Name: clinical_study clinical_study_reference_code_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_study
    ADD CONSTRAINT clinical_study_reference_code_key UNIQUE (reference_code);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: patients_patient patients_patient_patient_code_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_patient_code_key UNIQUE (patient_code);


--
-- Name: patients_patient patients_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_pkey PRIMARY KEY (id);


--
-- Name: reports_report reports_report_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.reports_report
    ADD CONSTRAINT reports_report_pkey PRIMARY KEY (id);


--
-- Name: reports_report reports_report_study_id_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.reports_report
    ADD CONSTRAINT reports_report_study_id_key UNIQUE (study_id);


--
-- Name: studies_endoscopicimage studies_endoscopicimage_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_endoscopicimage
    ADD CONSTRAINT studies_endoscopicimage_pkey PRIMARY KEY (id);


--
-- Name: studies_inferenceresult studies_inferenceresult_image_id_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_inferenceresult
    ADD CONSTRAINT studies_inferenceresult_image_id_key UNIQUE (image_id);


--
-- Name: studies_inferenceresult studies_inferenceresult_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_inferenceresult
    ADD CONSTRAINT studies_inferenceresult_pkey PRIMARY KEY (id);


--
-- Name: studies_modelconfig studies_modelconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_modelconfig
    ADD CONSTRAINT studies_modelconfig_pkey PRIMARY KEY (id);


--
-- Name: studies_study studies_study_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_study
    ADD CONSTRAINT studies_study_pkey PRIMARY KEY (id);


--
-- Name: studies_study studies_study_reference_code_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_study
    ADD CONSTRAINT studies_study_reference_code_key UNIQUE (reference_code);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_user_email_2220eff5_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX authentication_user_email_2220eff5_like ON public.authentication_user USING btree (email varchar_pattern_ops);


--
-- Name: authentication_user_groups_group_id_6b5c44b7; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);


--
-- Name: authentication_user_groups_user_id_30868577; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);


--
-- Name: authentication_user_user_permissions_permission_id_ea6be19a; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);


--
-- Name: authentication_user_user_permissions_user_id_736ebf7e; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);


--
-- Name: clinical_endoscopicimage_study_id_ceb9b8d5; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_endoscopicimage_study_id_ceb9b8d5 ON public.clinical_endoscopicimage USING btree (study_id);


--
-- Name: clinical_patient_doctor_id_b9985c6f; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_patient_doctor_id_b9985c6f ON public.clinical_patient USING btree (doctor_id);


--
-- Name: clinical_patient_patient_code_9a3617fe_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_patient_patient_code_9a3617fe_like ON public.clinical_patient USING btree (patient_code varchar_pattern_ops);


--
-- Name: clinical_report_generated_by_id_f1c7c1dd; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_report_generated_by_id_f1c7c1dd ON public.clinical_report USING btree (generated_by_id);


--
-- Name: clinical_study_doctor_id_56b40022; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_study_doctor_id_56b40022 ON public.clinical_study USING btree (doctor_id);


--
-- Name: clinical_study_patient_id_039f864b; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_study_patient_id_039f864b ON public.clinical_study USING btree (patient_id);


--
-- Name: clinical_study_reference_code_e1331d5c_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX clinical_study_reference_code_e1331d5c_like ON public.clinical_study USING btree (reference_code varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: patients_patient_doctor_id_1c263247; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX patients_patient_doctor_id_1c263247 ON public.patients_patient USING btree (doctor_id);


--
-- Name: patients_patient_patient_code_9ce8008e_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX patients_patient_patient_code_9ce8008e_like ON public.patients_patient USING btree (patient_code varchar_pattern_ops);


--
-- Name: reports_report_generated_by_id_17b52253; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX reports_report_generated_by_id_17b52253 ON public.reports_report USING btree (generated_by_id);


--
-- Name: studies_endoscopicimage_study_id_cf5dc089; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX studies_endoscopicimage_study_id_cf5dc089 ON public.studies_endoscopicimage USING btree (study_id);


--
-- Name: studies_study_doctor_id_e106b025; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX studies_study_doctor_id_e106b025 ON public.studies_study USING btree (doctor_id);


--
-- Name: studies_study_patient_id_765eb563; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX studies_study_patient_id_765eb563 ON public.studies_study USING btree (patient_id);


--
-- Name: studies_study_reference_code_0bf19275_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX studies_study_reference_code_0bf19275_like ON public.studies_study USING btree (reference_code varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: bladder_997
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_user_permissions authentication_user__permission_id_ea6be19a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_groups authentication_user__user_id_30868577_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_user_permissions authentication_user__user_id_736ebf7e_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_groups authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_endoscopicimage clinical_endoscopicimage_study_id_ceb9b8d5_fk_clinical_study_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_endoscopicimage
    ADD CONSTRAINT clinical_endoscopicimage_study_id_ceb9b8d5_fk_clinical_study_id FOREIGN KEY (study_id) REFERENCES public.clinical_study(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_inferenceresult clinical_inferencere_image_id_a7461e82_fk_clinical_; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_inferenceresult
    ADD CONSTRAINT clinical_inferencere_image_id_a7461e82_fk_clinical_ FOREIGN KEY (image_id) REFERENCES public.clinical_endoscopicimage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_patient clinical_patient_doctor_id_b9985c6f_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_patient
    ADD CONSTRAINT clinical_patient_doctor_id_b9985c6f_fk_authentication_user_id FOREIGN KEY (doctor_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_report clinical_report_generated_by_id_f1c7c1dd_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_report
    ADD CONSTRAINT clinical_report_generated_by_id_f1c7c1dd_fk_authentic FOREIGN KEY (generated_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_report clinical_report_study_id_8d3273ae_fk_clinical_study_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_report
    ADD CONSTRAINT clinical_report_study_id_8d3273ae_fk_clinical_study_id FOREIGN KEY (study_id) REFERENCES public.clinical_study(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_study clinical_study_doctor_id_56b40022_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_study
    ADD CONSTRAINT clinical_study_doctor_id_56b40022_fk_authentication_user_id FOREIGN KEY (doctor_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clinical_study clinical_study_patient_id_039f864b_fk_clinical_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.clinical_study
    ADD CONSTRAINT clinical_study_patient_id_039f864b_fk_clinical_patient_id FOREIGN KEY (patient_id) REFERENCES public.clinical_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patient patients_patient_doctor_id_1c263247_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_doctor_id_1c263247_fk_authentication_user_id FOREIGN KEY (doctor_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_report reports_report_generated_by_id_17b52253_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.reports_report
    ADD CONSTRAINT reports_report_generated_by_id_17b52253_fk_authentic FOREIGN KEY (generated_by_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reports_report reports_report_study_id_f4d132b4_fk_studies_study_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.reports_report
    ADD CONSTRAINT reports_report_study_id_f4d132b4_fk_studies_study_id FOREIGN KEY (study_id) REFERENCES public.studies_study(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studies_endoscopicimage studies_endoscopicimage_study_id_cf5dc089_fk_studies_study_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_endoscopicimage
    ADD CONSTRAINT studies_endoscopicimage_study_id_cf5dc089_fk_studies_study_id FOREIGN KEY (study_id) REFERENCES public.studies_study(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studies_inferenceresult studies_inferenceres_image_id_e2f2281f_fk_studies_e; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_inferenceresult
    ADD CONSTRAINT studies_inferenceres_image_id_e2f2281f_fk_studies_e FOREIGN KEY (image_id) REFERENCES public.studies_endoscopicimage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studies_study studies_study_doctor_id_e106b025_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_study
    ADD CONSTRAINT studies_study_doctor_id_e106b025_fk_authentication_user_id FOREIGN KEY (doctor_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studies_study studies_study_patient_id_765eb563_fk_patients_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.studies_study
    ADD CONSTRAINT studies_study_patient_id_765eb563_fk_patients_patient_id FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: bladder_997
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict jbxeNn20nM1EmiXef93FbzR9jtBXiFNLv240bKPASSeF7VlxbDK3MGUceOjyYP0

