# Generated by Django 5.2.14 on 2026-05-23 08:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndoscopicImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('width_px', models.PositiveIntegerField()),
                ('height_px', models.PositiveIntegerField()),
                ('image_quality', models.CharField(blank=True, choices=[('good', 'Good'), ('acceptable', 'Acceptable'), ('poor', 'Poor')], max_length=16)),
                ('source', models.CharField(blank=True, choices=[('camera', 'Camera'), ('gallery', 'Gallery')], max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120)),
                ('model_version', models.CharField(max_length=64)),
                ('inference_server_url', models.URLField()),
                ('onnx_optimization', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('model_file_path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=120)),
                ('model_version', models.CharField(max_length=64)),
                ('primary_label', models.CharField(choices=[('HGC', 'High Grade Cancer'), ('LGC', 'Low Grade Cancer'), ('NST', 'Non-Specific Tissue'), ('NTL', 'Normal Tissue')], max_length=8)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8)),
                ('is_malignant', models.BooleanField()),
                ('confidence_breakdown', models.JSONField()),
                ('analyzed_parameters', models.JSONField()),
                ('cellular_density', models.CharField(blank=True, choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High')], max_length=16)),
                ('nuclear_atypia', models.CharField(blank=True, choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=16)),
                ('mitotic_rate', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=16)),
                ('findings_overview', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('mask_url', models.URLField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inference_result', to='studies.endoscopicimage')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('study_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='endoscopicimage',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endoscopic_images', to='studies.study'),
        ),
    ]
