# Generated by Django 5.2.14 on 2026-06-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endoscopicimage',
            name='file_path',
        ),
        migrations.AddField(
            model_name='endoscopicimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='endoscopic/'),
        ),
        migrations.AlterField(
            model_name='endoscopicimage',
            name='file_size_mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='endoscopicimage',
            name='height_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endoscopicimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='endoscopicimage',
            name='width_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
