# Generated by Django 5.2.14 on 2026-05-23 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=32)),
                ('institution_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('include_images', models.BooleanField(default=True)),
                ('send_to_ehr', models.BooleanField(default=False)),
                ('physician_signature', models.BooleanField(default=False)),
                ('pdf_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='generating', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='studies.study')),
            ],
        ),
    ]
